@startuml
' use this pragma to have the elseif tests in vertical mode'
!pragma useVerticalIf off 'off, on'

title ffplay main

start
:avdevice_register_all;
:avformat_network_init;
partition "stream_open" {
  :av_mallocz -> VideoState;
  :frame_queue_init->videoq/audioq/subtitleq;
  :packet_queue_init->videoq/audioq/subtitleq;
  :init_clock->videoq/audioq/subtitleq;
  :SDL_CreateThread(read_thread);
}

partition "read_thread" {
  :av_packet_alloc;
  :avformat_alloc_context;
  :avformat_open_input;
  :avformat_find_stream_info;
  :av_find_best_stream;
  :stream_component_open;

    while (not abort request)
      :av_read_frame;
    endwhile
}

partition "event_loop" {
  while (input_stream is not null)
    :handle control message;
  endwhile
  :end of input stream;
}

stop

@enduml